import type { Meta, StoryObj } from '@storybook/react';
import ToolTip from './Tooltip';
import './Tooltip.scss';
declare const meta: Meta<typeof ToolTip>;
export default meta;
type Story = StoryObj<typeof ToolTip>;
export declare const All: Story;
export declare const IconUp: Story;
export declare const IconDown: Story;
export declare const IconRight: Story;
export declare const IconLeft: Story;
export declare const TextUp: Story;
export declare const TextDown: Story;
export declare const TextRight: Story;
export declare const TextLeft: Story;
export declare const IconTextUp: Story;
export declare const IconTextDown: Story;
export declare const IconTextRight: Story;
export declare const IconTextLeft: Story;
