import { Meta, StoryObj } from '@storybook/react';
import Switch from './Switch';
declare const meta: Meta<typeof Switch>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Disabled: Story;
export declare const Loading: Story;
export declare const SmallSize: Story;
export declare const LargeSize: Story;
export declare const TopPosition: Story;
export declare const BottomPosition: Story;
export declare const StartPosition: Story;
export declare const EndPosition: Story;
